spring:
  application:
    name: financial-tracker

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        globally_quoted_identifiers: true
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:/db/db.changelog-master.xml

springdoc:
  swagger-ui:
    path:
      /swagger-ui.html

server:
  port: 9090